### ISSUE TITLE
Listar os Pets na página Home

### ISSUE THREAD

**Issue by dawidsongru** [ijbs-dev/SosPet#23]
Descrição:

Como usuário, gostaria de visualizar os Pets cadastrados no Sistema.

Critérios de aceite:

– O usuário poderá visualizar os Pets mesmo que não esteja cadastrado no Sistema.
– Serão listados os últimos 6 Pets cadastrados.

**Comment by VictorLemos1000** [comment]
Finalizado tela de listar os pets na página Home.
